### PR TITLE
jetstream pull subscription allow waiting forever for next message

### PR DESCRIPTION
**Pull request by databasedav**
addresses https://github.com/nats-io/nats.py/issues/232

### CODE REVIEW

**Review by wallyqs — APPROVED** [review]
LGTM

**Comment by databasedav** [comment]
@wallyqs looks like the CI is failing, although the test i added passes locally. are there anymore docs or do u have any tips for running the tests? i also noticed that sometimes the nats-server didn't reset between failed runs, do i need to do that manually somehow? thanks!

**Comment by wallyqs** [comment]
@databasedav thanks for the contribution, try running `make format` and push again to fix the CI issues.

**Review by wallyqs — CHANGES_REQUESTED** [review]
`tests/test_js.py::PullSubscribeTest::test_fetch_one` might need some fixing, taking another look CI results after formatting fixed and green run.

**Review by wallyqs — APPROVED** [review]
LGTM!

**Pull request merged**
