### PR TITLE
Decrease pending_size when dequeue a message in request.wait_for_msgs

### PR DESCRIPTION
**Pull request by laishzh**
Decrease pending_size when dequeue a message in request.wait_for_msgs. #113

### CODE REVIEW

**Comment by vshender** [comment]
Why don't you make a release for this fix? It's a critical problem, and these changes are not in any release version of the library yet.

**Comment by wallyqs** [comment]
@vshender apologies... I just cut the release including this fix, thanks.
https://pypi.org/project/asyncio-nats-client/0.10.0/

**Comment by vshender** [comment]
@wallyqs thank you very much!

**Comment by abhaira** [comment]
I see the same bug for pull subscribers. Are they handled as part of this request?

**Comment by wallyqs** [comment]
His @abhaira maybe try with latest version, it should be fixed there for pull subscribers too.

**Comment by abhaira** [comment]
@wallyqs Thanks for the response. I have checked the code on the latest version. The code is there to subtract the queue byte size upon consumption of a message. I will test it and confirm. Thanks again.

**Pull request merged**
