### PR TITLE
Header support +  JetStream support + KV Store support

### PR DESCRIPTION
**Pull request by charbonnierg**
## Description

 This PR is based on the branch [`js-ctx`](https://github.com/nats-io/nats.py/tree/js-ctx) rebased on `master`.

It brings some changes related to >= NATS 2.2 usage as well as a JetStream API interface and KV Interface.

I know that it's a lot of changes, and maintainers might not want to introduce so many changes at once, so it's OK to refuse or ask for modifications. I hope this PR will help at least in identifying definitive JetStream API interface for NATS.

This PR supersedes #208 ,  #194, #178, #121 

## New Features

- [x] Header support: `Client.publish` and `Client.request` accept a new `headers` parameter which **must be a dictionary of strings** (dict values which are not string lead to error).
- [x] `NoResponder` support. Requesting on a subject without available responder will raise a `ErrNoResponder` exception
- [x] Subscription: `Client.subscribe(...)` returns a `Subscription` instance. If `cb` parameter is omitted or `None`, messages are stored in the `Subscription` instance and can be iterated upon (`async for msg in sub.messages`) or fetched one by one `await sub.next_msg()`.
- [x] Async context manager: It's still necessary to connect the client using `await nc.connect(...)` but client is automatically closed on context exit.
- [x] Type Annotations: All code is annotated and checked using `mypy`
- [ ] JetStream API support
- [ ] JetStream KV support
- [ ] Lame Duck Mode support.  A callback `lame_duck_mode_cb` can be provided and will be submitted as a task when receiving Lame Duck Mode info from server

## Deprecated Features

- [x] `Client.publish_request` should be removed in incoming versions. It's still present for backward compatibility but deprecated.

## Breaking Changes

- [x] `Client.subscribe(...)` returns a `Subscription` instance now instead of an `int`
- [x] `Client.unsubscribe` has been removed.
- [x] `Client.stats` is a dataclass and no longer a dictionary. As such, it is no longer iterable nor sliceable

## Minor Changes

- [x] `Client._server_info` is a dataclass and no longer a dictionary. This should be a minor change as attribute is exposed as private (prefixed with `_`)
- [x] Client no longer always raise exception instances instead of classes. As such, default error callback now displays correct exception info.
 
## Test Changes

- [x] `nats.aio.js` subpackage is almost entirely covered by unit tests defined in `tests/test_client_v2.py`
- [ ] Some new features introduced into `nats.aio.client.Client` or `nats.aio.messages.Msg` are not tested yet

###
## Codebase Changes

- [x] The `nats.aio.client` module is all messed up, I put public methods first, then private methods and finally private asynchronous methods. I find it easier this way to idenify where a method is located at a glance, but It can be reverted back if it's a problem.
- [x]  `nats.aio.client` module has been splitted into several modules in order to avoid circular imports or multiple definitions of constants
- [x] `nats.aio.js` subpackage has been introduced to provide JetStream API support
- [x] All code has been formatted using `yapf` as it seems to be the formatter used in this project

### Current test coverage

image

### JetStream API

- [x] Use a custom domain: `js = nc.jetstream(domain="edge")`
- [x] Acknowledge a message: `await msg.ack()`
- [x] Acknowledge a message and wait for confirmation: `await msg.ack_sync()`
- [x] `Nak`: negative acknowledgment indicating processing failed and the message should be resent later: `await msg.nak()`
- [x] `Term`:  Never send this message again, regardless of configuration: `await msg.term()`
- [x] `InProgress`: The message is being processed and reset the redelivery timer in the server. The message must be acknowledged later when processing is complete: `await msg.in_progress()`

#### Account Info

- [x] Get account info: `await js.account_info()`

#### Streams

- [x] List streams: `await js.stream.list(...)`
- [x] List stream names (optionally lookup by subject): `await js.stream.names(...)`
- [x] Create a stream: `await js.stream.add(...)`
- [x] Read stream info: `await js.stream.info()`
- [x] Update stream: `await js.stream.update(...)`
- [x] Delete stream: `await js.stream.delete(...)`
- [x] Purge stream: `await js.stream.purge(...)`
- [x] Get stream message: `await js.stream.msg_get(...)`
- [x] Delete stream message: `await js.stream.msg_delete(...)`

#### Consumers

- [x] Create a consumer (ephemeral or durable): `await js.consumer.add(...)`
- [x] Read consumer info: `await js.consumer.info(...)`
- [x] Delete a consumer: `await js.consumer.delete(...)`
- [x] Get consumer next message is possible but implementation might be bad: `await js.consumer.pull_next(...)`
- [ ] Iterate over consumer messages is possible but implementation might be bad: `async for msg in js.consumer.pull_msgs(...)`

#### KV Store

- [x] Create a bucket: `await js.kv.add("foo")`
- [x] Delete a bucket: `await js.kv.rm("foo")`
- [x] Put a value: `await js.kv.add("foo", "bar", b"1")` 
- [x] Get a value: `await js.kv.get("foo", "bar")`
- [x] Delete a key: `await  js.kv.delete("foo", "bar")`
- [x] Get a key history: `await js.kv.history("foo", "bar")`

### CODE REVIEW

**Comment by charbonnierg** [comment]
`tests/test_client.py::ClientTest::test_subscribe_no_echo` is flaky and fails with a `TimeoutError` sometimes

**Comment by jgerry2002** [comment]
Any chance we will see a merge of this? It seems to work well in testing.

**Comment by jgerry2002** [comment]
There appears to be a bug with this and the latest 2.6.1 version of nats-server. Its unable to create any streams. 2.4.0 works fine. Not sure if its appropriate to place this issue here or not.

Traceback (most recent call last):
  File "/home/test/natsclient/another_test.py", line 120, in <module>
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/test/natsclient/another_test.py", line 32, in main
    create_res = await js.stream.add("teststream",subjects=["test.>"])
  File "/home/test/python39/lib/python3.9/site-packages/nats/aio/js/api/stream.py", line 142, in add
    await self._js._request(
  File "/home/test/python39/lib/python3.9/site-packages/nats/aio/js/client.py", line 79, in _request
    result: ResponseT = response_dc(**data)
TypeError: __init__() got an unexpected keyword argument 'did_create'

**Comment by orsinium** [comment]
The error mentioned above (`TypeError: __init__() got an unexpected keyword argument 'did_create'`) is still there, I've addressed it in https://github.com/charbonnierg/nats.py/pull/6

**Comment by databasedav** [comment]
why was this closed? these additions are significantly more feature rich and ergonomic than the support that was "officially" released recently.

**Comment by orsinium** [comment]
This PR had some good ideas and a nicer API but (as I see it) it's too big to be merged in a reasonable amount of time. It has 3-in-1 right in the title, and inside of it a bunch of breaking changes. It all had to be carefully tested, reviewed, there were multiple things to fix (I commented on some of them), which depends on the author's availability (who's not paid for this work and so can't invest in it much). Before this PR was closed, I even wanted to take the initiative and bring this PR piece-by-piece as a bunch of smaller PRs. I also don't like the API and internals of what ended up in the `master` branch but I'm glad the project moves in that direction. "Progress over perfection"

**Pull request closed without merging**
