### PR TITLE
Fix python3.7, 3.8 compability

### PR DESCRIPTION
**Pull request by Lancetnik**
Fix all python3.9 annotation features to compatible codebase with python3.7, 3.8.
Changes only at annotations. Mypy and pytest runs OK.

### CODE REVIEW

**Comment by Lancetnik** [comment]
Release 2.3.0 breaks old python version, please fix it as soon as possible.

**Comment by wallyqs** [comment]
@Lancetnik if this is all it takes to support those versions I think it makes sense, would you mind running `make format` and updating?

**Comment by Lancetnik** [comment]
Sorry, but I have no all your Makefile dependencies on my PC. Like `yapf`

**Comment by Lancetnik** [comment]
LAO, it's a pip package... Sorry
The job is done

**Comment by wallyqs** [comment]
thanks! will merge and release then.

**Comment by wallyqs** [comment]
@Lancetnik pushed version [v2.3.1](https://github.com/nats-io/nats.py/releases/tag/v2.3.1) with your fixes fyi, thanks for the contribution 👍

**Comment by Lancetnik** [comment]
Thanks for release so fast!

**Comment by justinfx** [comment]
Hi. Just FYI, there is not v2.3.1 listed on the Release page, which made me think 2.3.0 was the latest source release and I just hit this bug.

**Comment by justinfx** [comment]
Also, I have just tested 2.3.1 against python 3.7 and it is still broken.
https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.get_name
```
Traceback (most recent call last):
  File ".../nats/js/client.py", line 795, in fetch
    msg = await self._fetch_one(expires, timeout)
  File ".../nats/js/client.py", line 835, in _fetch_one
    msg = await self._sub.next_msg(timeout)
  File ".../nats/aio/subscription.py", line 181, in next_msg
    task_name = future.get_name()
```

**Pull request merged**
